name: apiverve_ipblacklistlookup
description: IP Blacklist Lookup checks whether a given IP address appears on known malicious IP blocklists. Identifies both inbound threats (attackers, spammers) and outbound threats (C2 servers, malware hosts).
version: 1.1.14
homepage: https://apiverve.com/marketplace/ipblacklistlookup?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/ipblacklistlookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
